### ISSUE TITLE
I have to get four computer to run  mlp_mnist_dist.py?

### ISSUE THREAD

**Issue by wlmnzf** [dsindex/tensorflow#1]
I have two computer ,I want to try distributed tensorflow,so I run  
`python mlp_mnist_dist.py --ps_hosts=192.168.1.102:2223  --worker_hosts=192.168.1.105:2223  --job_name=ps --task_index=0
`
in one computer
and run
`python mlp_mnist_dist.py --ps_hosts=192.168.1.102:2223  --worker_hosts=192.168.1.105:2223  --job_name=worker --task_index=0
`
in another  computer,They connect successfully  but don't have any output information,so Is this normal?

**Comment by dsindex** [comment]
@wlmnzf  i got the same problem ;;

try this : 

nohup python ${CDIR}/mlp_mnist_dist.py --ps_hosts=localhost:2222 \
           --worker_hosts=localhost:2224 \
           --job_name=ps --task_index=0 &

python ${CDIR}/mlp_mnist_dist.py --ps_hosts=localhost:2222 \
           --worker_hosts=localhost:2224 \
           --job_name=worker --task_index=0

./mlp_mnist_dist.sh
